[package]
name = "kaku-gui"
version = "0.17.0"
authors = ["Tw93 <hitw93@gmail.com>"]
edition = "2018"
build = "build.rs"
resolver = "2"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "kaku_gui_lib"
path = "src/lib.rs"

[[bin]]
name = "kaku-gui"
path = "src/main.rs"

[[bin]]
name = "k"
path = "src/bin/k.rs"

[features]
default = ["vendored-fonts"]
distro-defaults = ["config/distro-defaults"]
vendor-nerd-font-symbols-font = ["wezterm-font/vendor-nerd-font-symbols"]
vendor-jetbrains-font = ["wezterm-font/vendor-jetbrains"]
vendor-roboto-font = ["wezterm-font/vendor-roboto"]
vendor-noto-emoji-font = ["wezterm-font/vendor-noto-emoji"]
vendored-fonts = [
  "vendor-nerd-font-symbols-font",
  "vendor-jetbrains-font",
  "vendor-roboto-font",
  "vendor-noto-emoji-font"
]
dhat-heap = ["dhat"]    # if you are doing heap profiling
dhat-ad-hoc = ["dhat"]  # if you are doing ad hoc profiling
remote = ["dep:kaku-remote"]

[build-dependencies]
anyhow.workspace = true

[target.'cfg(windows)'.build-dependencies]
cc.workspace = true
embed-resource.workspace = true

[dependencies]
anyhow.workspace = true
kaku-ai-utils.workspace = true
kaku-unicode-names.workspace = true
base64.workspace = true
bitflags.workspace = true
bytemuck.workspace = true
chrono.workspace = true
clap.workspace = true
codec.workspace = true
colorgrad.workspace = true
config.workspace = true
dhat = {workspace=true, optional=true}
dirs-next.workspace = true
downcast-rs.workspace = true
emojis.workspace = true
env-bootstrap.workspace = true
euclid.workspace = true
fastrand.workspace = true
finl_unicode.workspace = true
frecency.workspace = true
futures.workspace = true
getrandom.workspace = true
hdrhistogram.workspace = true
hostname.workspace = true
http_req.workspace = true
ignore.workspace = true
image.workspace = true
lazy_static.workspace = true
lfucache.workspace = true
libc.workspace = true
log.workspace = true
luahelper.workspace = true
metrics.workspace = true
mlua = {workspace=true, features=["send", "serialize"]}
kaku-remote = { workspace = true, optional = true }
mux-lua.workspace = true
mux.workspace = true
nucleo-matcher.workspace = true
ordered-float.workspace = true
parking_lot.workspace = true
portable-pty = { workspace=true, features = ["serde_support"]}
promise.workspace = true
rangeset.workspace = true
rayon.workspace = true
rust-i18n.workspace = true
serde = {workspace=true, features = ["rc", "derive"]}
reqwest = { workspace = true, features = ["blocking", "json"] }
regex.workspace = true
serde_json.workspace = true
rustyline.workspace = true
toml.workspace = true
shlex.workspace = true
smol.workspace = true
tabout.workspace = true
syntect.workspace = true
termwiz-funcs.workspace = true
termwiz.workspace = true
textwrap.workspace = true
tiny-skia.workspace = true
umask.workspace = true
unicode-segmentation.workspace = true
url-funcs.workspace = true
url.workspace = true
wezterm-bidi.workspace = true
wezterm-blob-leases = { workspace=true, features=["simple_tempdir"] }
wezterm-client.workspace = true
wezterm-dynamic.workspace = true
wezterm-font.workspace = true
wezterm-gui-subcommands.workspace = true
wezterm-mux-server-impl.workspace = true
wezterm-open-url.workspace = true
# wezterm-ssh.workspace = true
wezterm-term = { workspace = true, features = ["use_serde"] }
bincode.workspace = true
wezterm-toast-notification.workspace = true
wgpu.workspace = true
window-funcs.workspace = true
window.workspace = true

[target.'cfg(target_os="macos")'.dependencies]
cocoa.workspace = true
objc.workspace = true

[target.'cfg(windows)'.dependencies]
shared_library.workspace = true
winapi = { workspace=true, features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
    "winsock2",
]}
windows = { workspace=true, features = [
    "Win32_UI_Shell",
]}

[dev-dependencies]
benchmarking.workspace = true
env_logger.workspace = true
k9.workspace = true
tempfile.workspace = true

[lints]
workspace = true
